# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty
relative_permalinks: true


# Setup
title:            Otterly Offensive
tagline:          'When Otters Rule the World'
description:      'The following code will be offensive.'
url:              https://otterlyoffesnive.com
baseurl:          /

author:
  name:           'roobixx'
  url:            https://twitter.com/roobixx
  
paginate:         5

         
