# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty


# Setup
title:            Ottely Offensive
tagline:          'When Otters Rule the World'
description:      'When Otters Rule the World'
url:              https://otterlyoffesnive.com
baseurl:          /

author:
  name:           'roobixx'
  url:            https://twitter.com/roobixx

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           
