# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty


# Setup
title:            Ottely Offensuve
tagline:          'When Otters Rule the World'
description:      'A brazen two-column <a href="http://jekyllrb.com" target="_blank">Jekyll</a> theme that pairs a prominent sidebar with uncomplicated content. Made by <a href="https://twitter.com/mdo" target="_blank">@mdo</a>.'
url:              https://otterlyoffesnive.com
baseurl:          /

author:
  name:           'roobixx'
  url:            https://twitter.com/roobixx

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           
