# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty


# Setup
title:            Ottely Offensive
tagline:          'When Otters Rule the World'
description:      'The following code will be offensive.'
url:              https://otterlyoffesnive.com
baseurl:          /

author:
  name:           'roobixx'
  url:            https://twitter.com/roobixx

         
